#ifndef JIFFIE_VERSION_H
#define JIFFIE_VERSION_H

// These should come through CMake
#ifndef JIFFIE_MAJOR
#define JIFFIE_MAJOR 0
#endif
#ifndef JIFFIE_MINOR
#define JIFFIE_MINOR 0
#endif
#ifndef JIFFIE_BUILD
#define JIFFIE_BUILD 0
#endif
#ifndef JIFFIE_COMMIT_HASH
// Default to the first commit
#define JIFFIE_COMMIT_HASH "260ac10a0198622de790ac757d7b4a5ffc0811c6"
#endif


#define JIFFIE_STRINGIFY_INNER(x) #x
#define JIFFIE_STRINGIFY_OUTER(x) JIFFIE_STRINGIFY_INNER(x)

#define JIFFIE_VERSION \
	JIFFIE_STRINGIFY_OUTER(JIFFIE_MAJOR) "." \
	JIFFIE_STRINGIFY_OUTER(JIFFIE_MINOR) "." \
	JIFFIE_STRINGIFY_OUTER(JIFFIE_BUILD)

#define JIFFIE_VERSION_LONG \
	JIFFIE_STRINGIFY_OUTER(JIFFIE_MAJOR) "." \
	JIFFIE_STRINGIFY_OUTER(JIFFIE_MINOR) "." \
	JIFFIE_STRINGIFY_OUTER(JIFFIE_BUILD) ".0"

#endif // JIFFIE_VERSION_H
